name: Build

on:
  push:
    branches:
      - master
      - develop
      - main
      - 'feature/**'
      - 'bugfix/**'

jobs:
  build:
    runs-on: self-hosted
    steps:
      - uses: actions/checkout@v3

      - name: Verificar SQL nos commits
        shell: cmd
        run: .\check_sql.bat

      - name: compile-project
        shell: powershell
        run: .\compilador.bat
